### ISSUE TITLE
dhall format: automatically pun record entries of key and value name is the same

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#1731] opened 2020-03-30 21:39 UTC
I’ve been structuring all my dhall files like this in expectation of pun support:

```
in  { K = K
    , T = T
    , Timestamp = Timestamp
    , mkTimestamp = mkTimestamp
    , Resource = Resource
    , Talk = Talk
    , TvShow = TvShow
    , Podcast = Podcast
    , Person = Person
    , Interview = Interview
    }
```

My hope was that `dhall format` would automatically convert fields where the name and value are the same to their punned version.

**Comment by Gabriel439** [comment] 2020-03-30 21:43
This is a duplicate of https://github.com/dhall-lang/dhall-haskell/issues/1728 which was just fixed by https://github.com/dhall-lang/dhall-haskell/pull/1729

**Closed by Gabriel439** 2020-03-30 21:43 UTC
Labels: enhancement, formatting
