### ISSUE TITLE
Empty list type annotation can't be a type synonym

### ISSUE THREAD

**Issue by blamario** [dhall-lang/dhall-haskell#935] opened 2019-05-03 21:09 UTC
This fails to normalize  with `Error: An empty list requires a type annotation`

```
   let ListOfPairs = List {_1 : Text, _2 : Text}
in let empty = [] : ListOfPairs
in empty
```

The  workaround is to manually expand `: ListOfPairs` into `: List {_1 : Text, _2 : Text}`.

**Comment by f-f** [comment] 2019-05-03 21:21
This comes up pretty often, in fact we also have [a FAQ entry about it](https://github.com/dhall-lang/dhall-lang/wiki/Frequently-Asked-Questions-(FAQ)#why-cant-i-use-a-type-alias-on-an-empty-list) 🙂

Let's close it as I think it's a duplicate of #414

**Closed by f-f** 2019-05-03 21:21 UTC

**Comment by f-f** [comment] 2019-05-03 21:22
Also I'll note that the following works too:

```hs
let Pairs = {_1 : Text, _2 : Text}
let empty = [] : List Pair
in empty
```

**Comment by blamario** [comment] 2019-05-03 21:28
Okay, thank you. I understand the reasoning, but I'm not surprised it's a FAQ. Sorry I didn't read it beforehand.

**Comment by f-f** [comment] 2019-05-03 21:31
No worries! 🙂

**Comment by Gabriel439** [comment] 2019-05-04 00:28
Note that this may be fixable in the future (by turning it into a type error instead of a parse error), but it's low on the list of things to improve

**Comment by PierreR** [comment] 2019-10-01 09:29
@Gabriel439 Is the above issue related to the same FAQ ?

Given this type declared in Mr.dhall:
```
let Mr
    : Type
    = { config : List Text
      , templateUrl : Text
      , repos : List Text
      }
in  Mr
```
I was hoping to be able to remove the type annotion in this record:

```
{ config = [] 
, templateUrl = ""
, repos = [] 
} : ./Mr.dhall
```
But it actually fails with : 
`Error: An empty list requires a type annotation`

Is this something that also could be supported in the future ?

**Comment by sjakobi** [comment] 2019-10-01 13:52
@PierreR Your example would require that the type of the lists can be inferred from the type of the containing record. AFAIK there are no plans for supporting real type inference, since that would make it harder for new implementations.

I have removed the question regarding list annotations with type synonyms from the FAQ, since that has been supported for a while now.

**Comment by PierreR** [comment] 2019-10-01 18:55
Fair enough. The ability to  "check" a configuration file with a spec/type would be such a great feature, a bit like schema in xml/json/yaml. 

Correct me if I am wrong but in the current situation you go into the trouble of defining a schema/type and in return you still need to annotate your configuration with type . That sound totally counter-intuitive to me ... FWIW for now I will just remove the Type file. I don't see the point of it at least for my little use case.

**Comment by PierreR** [comment] 2019-10-01 19:05
What I find quite confusing as a curious Dhall user is the fact that Dhalls support a certain level of type inference but at the same time I don't know what kind of level that is.

In that regard the above described behavior had been quite a surprise (I take here the mere user point of view leaving aside implementation/technical details ....).

**Comment by PierreR** [comment] 2019-10-01 19:15
If the concern is about new implementations, some features like this (if they are considered important by many) could be guarded with a pragma and left optional in the standard ?

**Comment by Gabriel439** [comment] 2019-10-02 01:28
@PierreR: I'm opposed to pragmas/extensions.  That's how GHC drove out competing implementations in the Haskell ecosystem
