### ISSUE TITLE
Integrity check for `as Text` import using sha256 of the empty string breaks integrity  

### ISSUE THREAD

**Issue by shonfeder** [dhall-lang/dhall-haskell#2067] opened 2020-10-12 03:41 UTC
The following configuration compiles, even when `non-existent.txt` doesn't exist:

```dhall
let v =
      ./non-existent.txt sha256:f08ed5225480d827ff3ce74b756afa6330f66d974d6f0d6160d767b5c45642aa as Text

in  { v }
```

This seems to be because the has here is the unique hash of the empty file. So far so good.

But if we now add a file with some content:

```
$ cat existent.txt
There's text in here!
``` 

Then this configuration will compile if we reuse the same empty file hash:

```dhall
-- in bug.dhall
let v =
      ./existent.txt sha256:f08ed5225480d827ff3ce74b756afa6330f66d974d6f0d6160d767b5c45642aa as Text

in  { v }
```

```sh
$ dhall < bug.dhall 
{ v = "" }
```

This effectively breaks the integrity check, since no matter what content we put in `existent.txt`, the config will compile without complaint.

---

System info:

```sh
$ dhall --version
1.35.0
# From the arch repo

$ uname -a
Linux comp 5.4.67-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:20:18 UTC 2020 x86_64 GNU/Linux
```

**Comment by basile-henry** [comment] 2020-10-12 11:38
The integrity hashes are also used to query the dhall cache, so if the file content changes but the integrity hash doesn't and you have already seen this hash, then what was in the cache for that hash will be used instead. 

Your `non-existent.txt` example shouldn't work the first time if you don't already have the hash in your cache, you should get:

```
dhall:
↳ ./non-existent.txt sha256:f08ed5225480d827ff3ce74b756afa6330f66d974d6f0d6160d767b5c45642aa as Text

Error: Missing file ./non-existent.txt

2│       ./non-existent.txt sha256:f08ed5225480d827ff3ce74b756afa6330f66d974d6f0d6160d767b5c45642aa as Text

(input):2:7
```

I guess the reason you don't have that is because you have already imported an empty file before so your cache has the content corresponding to that hash.

Now if you don't want to use the cache, you can temporarily disable it with `--no-cache`. As far as I can tell what you are describing in this issue works as intended. But maybe it's not the most obvious behaviour?

Hope this helps :smile:

**Comment by Gabriel439** [comment] 2020-10-12 14:31
@shonfeder: Yeah, what @basile-henry says is correct.  The hash takes precedence over the import.  In fact, it's even legal for the following import to successfully resolve if the hash is present in the cache:

```dhall
missing sha256:f08ed5225480d827ff3ce74b756afa6330f66d974d6f0d6160d767b5c45642aa 
```

The reason why Dhall behaves this way is because if the underlying import had to be refetched then it would defeat the purpose of caching imports.

To address your original concern: note that the integrity check is not broken.  You did get back an expression that matched the integrity check (the empty `Text` literal).  You just didn't get back what was inside `./existent.txt`.  The integrity check doesn't necessarily guarantee that you will get what was inside the attached import, but it does guarantee that you will get back an expression that matches the hash.

**Comment by sjakobi** [comment] 2021-01-16 19:11
Closing since it seems that the import behaviour was sufficiently explained.

Please feel free to reopen if there's more to discuss.

**Closed by sjakobi** 2021-01-16 19:11 UTC

**Comment by shonfeder** [comment] 2021-01-17 21:53
Yes, all clear! Thank you very much for the patient explanation, I'm sorry I forgot to confirm resolution earlier! :pray
