### ISSUE TITLE
dhall format introduces unwanted leading space

### ISSUE THREAD

**Issue by lorenzo** [dhall-lang/dhall-haskell#1097] opened 2019-07-12 09:32 UTC
When nesting a `let` expression inside a function, `dhall format` always introduces some leading whitespace before the `in` keyword.

This is not a big problem, but does annoy me a little since I have enabled highlighting for additional whitespace in my editor.

This is the result of the formatter:

```dhall
let makeMasterProtection =
        λ ( repositories
          : List RepositoryConfig
          )
      → let makeGitlaBranchProtection =
                λ ( repository
                  : RepositoryConfig
                  )
              →   { mapKey =
                      "${repository.key}_${defaultBranchProtectionOptions.branch}"
                  , mapValue =
                        printableBranchProtectionOptions
                        defaultBranchProtectionOptions
                      ∧ { project = repository.name }
                  }
                : G.TF/GitLabBranchProtection
        
        in  map
            RepositoryConfig
            G.TF/GitLabBranchProtection
            makeGitlaBranchProtection
            repositories
```

This is how I see it in my editor:

![Screenshot 2019-07-12 at 11 30 15](https://user-images.githubusercontent.com/37621/61118262-a6af4780-a498-11e9-82f7-3103aa99a2b2.png)

**Comment by Gabriel439** [comment] 2019-07-13 02:43
@lorenzo: There's a work-in-progress pull request to fix this:

https://github.com/dhall-lang/dhall-haskell/pull/955

... but it still has some bugs that need to be fixed.  See:

https://github.com/dhall-lang/dhall-haskell/pull/955#issuecomment-509013210

**Comment by sjakobi** [comment] 2019-10-15 18:47
Closing as a duplicate of #183.

**Closed by sjakobi** 2019-10-15 18:47 UTC
Labels: formatting
