### ISSUE TITLE
Odd parsing error message

### ISSUE THREAD

**Issue by mt-caret** [dhall-lang/dhall-haskell#1743] opened 2020-04-08 08:07 UTC
Given the following input:

```
let FooType = < Foo : { foo : Text, baz : Natural } >
in FooType.Foo ({ foo = "bar" } // { baz = 01 })
```
Dhall gives the following error message:

```
dhall:
Error: Invalid input

(stdin):2:16:
  |
2 | in FooType.Foo ({ foo = "bar" } // { baz = 01 })
  |                ^
unexpected '('
expecting ->, :, end of input, operator, or whitespace
```

which is a bit puzzling, since the error is `bar = 01`, which should be `bar = 1`.

```
$ dhall --version
1.30.0
```

**Comment by sjakobi** [comment] 2020-04-08 13:45
I suspect this is just another instance of https://github.com/dhall-lang/dhall-haskell/issues/1592.

Gabriel has already started to prepare `dhall` for an eventual fix: https://github.com/dhall-lang/dhall-haskell/commit/477f42a4fdb76a20b4a8e152e5054e8bd04bfed0

**Comment by Gabriel439** [comment] 2020-04-08 13:45
This is essentially a duplicate of https://github.com/dhall-lang/dhall-haskell/issues/1592, so I'll close this issue in favor of that one

**Closed by Gabriel439** 2020-04-08 13:45 UTC
