### ISSUE TITLE
Loading from Cache Typechecks Again

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#642] opened 2018-10-16 17:35 UTC
It seems like we're not getting any wins from caching when it comes to caching. Correct me if I'm wrong (very likely 😄) but when we run `dhall <<< ./file` it will [resolve](https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Main.hs#L273) the expressions, this is where loading from the cache comes in, but it still [typechecks](https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Main.hs#L275) everything that was loaded. Could there be a way to keep the the inferred types of the cached files as well?

**Comment by sellout** [comment] 2018-10-16 17:38
So, we could potentially always cache `Annot`, but perhaps add a `checked` boolean to `Annot`, such that `typeWithA` doesn’t `loop` over `Annot` nodes that have been loaded from cache (i.e., `checked = True`)?

**Comment by Gabriel439** [comment] 2018-10-16 17:54
We could disable type-checking for things imported from the cache if we can lock down permissions such that only the user has read-write access to it.  We already type-check things before we cache them anyway

**Comment by FintanH** [comment] 2018-10-16 17:56
> We already type-check things before we cache them anyway

Ya, the hope is not to do that work the second time when loading from the cache 😁

**Comment by Gabriel439** [comment] 2018-10-16 18:00
Oh, I remember why we type-check things now.  Type-checking is necessary so that we can αβ-normalize the expression to verify the semantic integrity check.  So if we disable type-checking for imported expressions that implies disabling signature verification, too.

However, that could be an option.  Again, we can trust the cache if we can lock it down and assume cached expressions have been verified to match the semantic integrity check.

**Comment by FintanH** [comment] 2018-10-16 18:02
Does the semantic integrity check not happen before the place I pointed out above?

**Comment by Gabriel439** [comment] 2018-10-16 19:45
@FintanH: Oh, sorry.  I misunderstood which type-checking step you are referring to.

Yeah, this would require more work to prevent type-checking the resolved expression at least once.

Before deciding on a particular strategy, I would like to know:

* How large is the expression being type-checked (in bytes for the cached form)?
* How long does it take to type-check the expression after decoding it from the cache?

The reason I ask the first question is that I want to see if the problem is due to the expression having a very large normal form, because if that is the case maybe we can apply some language design to lead to more compact normal forms.

The second I ask the second question is to see if type-checking is in the right ballpark for performance or not, because I usually only resort to caching as a last resort for resolving performance issues.

**Comment by FintanH** [comment] 2018-10-17 14:13
@Gabriel439: This isn't regarding caching, but it'll give you an idea of what we're working with. I took a configuration that we can get to complete in a "reasonable" amount of time, about 14mins.

* Redirecting the output of `dhall <<< ./expression` results in ~550MB
* `dhall resolve` on that output takes about 16mins
* `dhall type` on the result of `dhall resolve` takes about 16mins

**Comment by FintanH** [comment] 2018-10-18 08:28
Update: The size of the cached file is 33MB

**Comment by Gabriel439** [comment] 2019-07-14 19:19
Closing as we no longer need to type-check expressions loaded from the binary cache.  See the relevant logic here:

https://github.com/dhall-lang/dhall-haskell/blob/b2cbc8227fa895133af95fab80c10d617535245a/dhall/src/Dhall/Import.hs#L478-L496

**Closed by Gabriel439** 2019-07-14 19:19 UTC
Labels: performance
