### ISSUE TITLE
Docker distribution

### ISSUE THREAD

**Issue by gregwebs** [dhall-lang/dhall-haskell#513] opened 2018-07-18 04:11 UTC
Are there any easy ways to distribute dhall (no requirement for installing any Haskell toolchain)? I can provide a Dockerfile.

**Comment by gregwebs** [comment] 2018-07-18 19:01
Let me know when you have a package and then I can create a Dockerfile with that. It's nice to have a sandboxed install that also works on Mac.

**Comment by f-f** [comment] 2018-07-18 19:20
@gregwebs we also have Dhall available in `nix`, which is pretty sandboxed ([more info here](https://nixos.org/nix/about.html), but it has many nice things, and system-wise "sandboxing" in that if you want to get rid of it you can just nuke the `/nix` folder).

Once you install `nix` (see [here](https://nixos.org/nix/download.html)) you can get `dhall` with `nix-env -iA nixpkgs.dhall`

**Comment by gregwebs** [comment] 2018-07-18 20:20
Great! I can probably also create a docker image with the nix package.

**Comment by PierreR** [comment] 2018-07-18 20:44
FWIW it is really easy to make a docker from a nix configuration without any Dockerfile. The image is usually better optimized in terms of size. You just need to use `dockerTools.buildImage`.

**Comment by Gabriel439** [comment] 2018-07-22 15:56
@gregwebs: We now have tarballs containing statically linked `dhall` and `dhall-to-{json,yaml}` executables for the latest releases.  You can get them here:

* https://github.com/dhall-lang/dhall-haskell/releases/download/1.16.1/dhall-1.16.1-x86_64-linux.tar.bz2
* https://github.com/dhall-lang/dhall-json/releases/download/1.2.2/dhall-json-1.2.2-x86_64-linux.tar.bz2

More generally, new releases going forward will continue to generate these tarballs so you can find them by visiting each project's Releases page:

* https://github.com/dhall-lang/dhall-haskell/releases
* https://github.com/dhall-lang/dhall-json/releases

These executables are completely statically linked so they'll work on any x86 64-bit Linux operating system, so you can probably create a `Dockerfile` that installs the above executables by doing something like:

```Dockerfile
RUN curl -O https://github.com/dhall-lang/dhall-haskell/releases/download/1.16.1/dhall-1.16.1-x86_64-linux.tar.bz2 && \
  tar xf dhall-1.16.1-x86_64-linux.tar.bz2 && \
  mv ./bin/dhall /usr/bin
RUN curl -O https://github.com/dhall-lang/dhall-json/releases/download/1.2.2/dhall-json-1.2.2-x86_64-linux.tar.bz2 && \
  tar xf dhall-json-1.2.2-x86_64-linux.tar.bz2 && \
  mv ./bin/dhall-to-{json,yaml} /usr/bin
```

**Comment by ocharles** [comment] 2018-10-28 22:43
I'm going to close this as we now distribute static binaries, which I think solves the same problem.

**Comment by Sir4ur0n** [comment] 2019-05-02 09:16
Hi, sorry to revive this closed issue, but I think a Docker image is different from static binaries.
A use case where a Docker image would be useful is build environments: in many companies, each build runs inside docker images to get full reproducibility. Being able to run a one-time Dhall command without installing it would be useful.

Ideally, something as simple to use as https://hub.docker.com/r/pinterb/jinja2/

Of course each person/group of persons can rebuild a Docker image for its own needs. But it would be simpler and faster to expose a Docker image on Docker Hub.

Unless there's a way to already do it that I missed?

Thank you

**Comment by f-f** [comment] 2019-05-02 09:34
@Sir4ur0n now that we have static binaries building a Docker image out of them is a two-line Dockerfile: we can use Alpine (because static binaries) and just `wget` the binaries into the image

**Comment by joneshf** [comment] 2019-05-02 13:49
I'm with @Sir4ur0n on this one. Rolling your own `Dockerfile` is more friction to getting started. Rolling a `Dockerfile` that can be `run` as a command is even harder. Since `dhall` doesn't read in arguments–it only reads from STDIN–it takes some knowledge of docker and shell scripting to write a `Dockerfile` that can be used like:
```sh
$ docker run dhall 123
```

The static binaries definitely make this easier (since we can use an `alpine` image, or even better a `scratch` image). But, it's still non-trivial to use `dhall` in docker.

**Comment by Profpatsch** [comment] 2019-05-02 17:49
Didn’t we add a `--file` flag? `docker run dhall --file ./foobar`.

**Comment by Gabriel439** [comment] 2019-05-02 18:19
@Profpatsch: Not yet.  The `--file` flag is still `TODO`

**Comment by Gabriel439** [comment] 2019-05-13 03:29
Pull request to build images in CI is up here: https://github.com/dhall-lang/dhall-haskell/pull/950

**Comment by Sir4ur0n** [comment] 2019-05-14 08:30
Thank you, this is a nice step forward! Any plan to release to [Docker hub](https://hub.docker.com)? This would be perfect as far as I'm concerned.

**Comment by Gabriel439** [comment] 2019-05-14 15:01
@Sir4ur0n: Yes, I will release to Docker hub when I cut the next release

**Comment by Sir4ur0n** [comment] 2019-05-14 15:58
Perfect it is then, again, thank you!

**Comment by Gabriel439** [comment] 2019-05-14 16:08
@Sir4ur0n: You're welcome! 🙂

**Comment by Allsimon** [comment] 2019-05-21 21:00
I can't get the docker image to work

```bash
➜  /tmp NAME="dhall-json"
➜  /tmp curl -s --location --remote-name "https://hydra.dhall-lang.org/job/dhall-haskell/master/image-${NAME}/latest/download/1/docker-image-${NAME}.tar.gz"
➜  /tmp docker load < "docker-image-${NAME}.tar.gz"
Loaded image: dhall-json:12kd8h7j4rql7xvzwbnvrx3f8mzidxjg
➜  /tmp docker run -i dhall-json:12kd8h7j4rql7xvzwbnvrx3f8mzidxjg dhall <<< '2 + 2'
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"dhall\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled


➜  /tmp sha512sum docker-image-${NAME}.tar.gz    
5700e79f1cac7daa9266bec78d611d1d032acaccc8d6dc304a7fdf89e8106f025c02eeee98c9bc9de8feae9a8aa6cfd5eb6d6f3102452b9ac440a72ac7ee3776  docker-image-dhall-json.tar.gz
```

Other containers works fine on my machine (so it doesn't seems to be [this issue](https://github.com/docker/for-linux/issues/561)).

**Comment by Gabriel439** [comment] 2019-05-21 22:30
@Allsimon: I believe this will work:

```bash
$ docker run -i dhall-json:12kd8h7j4rql7xvzwbnvrx3f8mzidxjg dhall-to-json <<< '2 + 2'
```

The main change is to run `dhall-to-json` instead of `dhall`, since each container only exposes executables for its respective Haskell package.

**Comment by Allsimon** [comment] 2019-05-22 17:30
My bad, I completely missed it :/

**Comment by Gabriel439** [comment] 2019-05-22 17:32
@Allsimon: No problem at all! 🙂

**Closed by Gabriel439** 2019-05-22 17:32 UTC

**Comment by Gabriel439** [comment] 2019-06-04 04:39
@Sir4ur0n: I've uploaded test containers to Docker Hub for the upcoming release if you want to give them a try:

* https://hub.docker.com/r/dhallhaskell/dhall/tags
* https://hub.docker.com/r/dhallhaskell/dhall-json/tags
* https://hub.docker.com/r/dhallhaskell/dhall-text/tags
* https://hub.docker.com/r/dhallhaskell/dhall-bash/tags

**Comment by Sir4ur0n** [comment] 2019-06-05 07:11
I confirm this works:
```
docker run -i dhallhaskell/dhall:1.24.0 dhall <<< '2 + 2'
docker run -i dhallhaskell/dhall-json:1.3.0 dhall-to-json <<< '2 + 2'
docker run -i dhallhaskell/dhall-text:1.0.18 dhall-to-text <<< '"Hello" ++ " world"'
docker run -i dhallhaskell/dhall-bash:1.0.21 dhall-to-bash <<< '2 + 2'
```

May I suggest 2 additional improvements, if it's not too much asked? (I can open another issue if it's easier to manage)

1. Provide in the overview a few lines to explain how to use this Docker image (in the same spirit as https://hub.docker.com/r/pinterb/jinja2/). This would decrease the time to first API call, which is always nice.
2. Push to the `latest` tag, so that it's possible to omit the tag and have an even simpler command for starters

Again, thank you for this piece of work! 😄

**Comment by Gabriel439** [comment] 2019-06-06 04:12
@Sir4ur0n: Alright, I added overviews and a `:latest` tag for each one.  Let me know if I missed anything

**Comment by Sir4ur0n** [comment] 2019-06-06 18:22
This is perfect, thank you! I really appreciate all the effort.

It's suddenly become much easier to start with Dhall 😍

**Comment by Gabriel439** [comment] 2019-06-06 18:29
@Sir4ur0n: You're welcome! 🙂
