### ISSUE TITLE
[Question] Static executables for Nix/NixOS

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#783] opened 2019-01-17 14:43 UTC
Is there a way to install the `dhall` static executable (and all other extensions like dhall-bash) in nix/nixos using something like:
```
nix-env -iA dhall -f https://github.com/dhall-lang/archive/v1.21.1.tar.gz
```
I am currently using a [custom derivation](https://github.com/PierreR/devbox-config/blob/master/default.nix) for this but maybe this is not necessary ?

**Comment by Gabriel439** [comment] 2019-01-18 06:10
@PierreR: This should work:

```bash
$ nix-env --install --attr dhall --file https://github.com/dhall-lang/dhall-haskell/archive/1.20.1.tar.gz
```

**Comment by PierreR** [comment] 2019-01-18 07:40
@Gabriel439 does it ? It seems to download ghc, ... I really want the static executables only.

**Comment by ocharles** [comment] 2019-01-18 08:45
I think you need Dhalls Hydra as a binary cache

**Comment by PierreR** [comment] 2019-01-18 09:48
@ocharles Well I just want to get the provided static executable. So that's what I do locally:
```
with import <nixpkgs> {};

let

# Instead of building from nixpkgs, use the provided static executable.
# By relying solely on the static executable, we don't care about the nix machinery that would build from source.
# (chances are that the version we want is not yet in the binary cache).
# For instance, building with nix using `nix-env -iA haskellPackages.dhall_1_20_1 -f https://github.com/NixOS/nixpkgs/archive/088cb13aee074fb48d104222cb80fb552ec17529.tar.gz `
# would currently pull 250M (unpacked) and then compile dhall ...
dhall =
  stdenv.mkDerivation rec {
    name = "dhall-${version}";
    version = "1.20.1";
    src = fetchurl {
        url = "https://github.com/dhall-lang/dhall-haskell/releases/download/1.20.1/dhall-${version}-x86_64-linux.tar.bz2";
        sha256 = "1ycb0pglwi9k1pn4qqjyvd4bi54000fb9aqxnn550a515rm6cb03";
    };

    installPhase = ''
      mkdir -p $out/bin
      cp dhall $out/bin/
    '';
  };
in
{
inherit dhall;
}
```
But maybe the repo could offer such a derivation if it doesn't already

**Comment by PierreR** [comment] 2019-01-18 09:50
@ocharles do you mean that if I set up the dhall binary cache I will get it with 
`$ nix-env --install --attr dhall --file https://github.com/dhall-lang/dhall-haskell/archive/1.20.1.tar.gz`

Sorry I read you comment too quickly ;-)

**Comment by ocharles** [comment] 2019-01-18 10:16
Yea. Nix can only download pre-built things if you trust the binary substituter. So you will have to trust https://hydra.dhall-lang.org (which is where the binaries are built).

**Comment by PierreR** [comment] 2019-01-18 10:37
@ocharles I will. I have just sett the cache and it works nicely. But still it pulls a lot of Mg compared to the tiny static executable. Why not favor the static executable ?

**Comment by PierreR** [comment] 2019-01-18 10:41
```
λ  ~ → nix-env -iA dhall -f https://github.com/dhall-lang/dhall-haskell/archive/1.20.1.tar.gz                                                                                                                                              1 ↵
copying path '/nix/store/2dxd77qqvgd71phnzryhvwigs7ad8nck-nix-2.0.4-man' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/llg71hai1vfgbb8smmzf55df8bfjp14s-glibc-2.27-bin' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/d60s5bwv6r3hl6w8cg5j7znwaiva43n8-gmp-6.1.2' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/2j519jciaav3d1x6rb5dzx4hnm2mfpla-gnumake-4.2.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/lay34qr1x11xllcs4bvfjrg4s91fprna-gnused-4.5' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/jndsxs0zwlr3yajpb4ms2l8gchaa089y-gnutar-1.30' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/722h7japzrsp0mp7p27mvgs4bm4wjngq-gzip-1.9' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/gdz5mjkkx1lmnspcciw5mdsrm5jy10wh-libatomic_ops-7.6.4' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/1wn9cbss7p0n2a179sas7cyrh73ddxwn-libffi-3.2.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/fjvakgw3ix4lp5w3cpph7f3fa5lknqb7-boehm-gc-7.6.6' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/6hcfz0lmkz60k6fz0k15gjnx4r1arylb-libffi-3.2.1-dev' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/lmym3gjdzlih2nhyswd7629cmrsdpk8j-libkrb5-1.15.2' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/r4n0amxzag2d23gh01ka0jwbfdszaygh-libseccomp-2.3.3-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/sjmajiy48jpznjlzfk37n7dq5zk8jd4v-libsodium-1.0.16' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/c3hbzv281h28g09v55974fjd5l2qbvxi-libtool-2.4.6-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/z7f3zgwk78fdsg9bm3h7iri3gpmcdv6y-linux-headers-4.15' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/w8bxy3xrvrd1ci5772y7arkicj0q7x3h-ncurses-6.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/z2v959r3xw6rr3srz5vfzv63dy7mq98i-glibc-2.27-dev' from 'https://cache.dhall-lang.org'
...
...
```
The fully static Haskell executables would be "<3 MB"

**Comment by Gabriel439** [comment] 2019-01-18 15:12
@PierreR: Yeah, if you need the static executables then we can provide top-level derivations for them

**Comment by PierreR** [comment] 2019-01-21 09:05
@Gabriel439 I don't understand why but it does not seem to work. The following command is still downloading the internet. I have also tried it locally with `nix-build -A dhall` with the same result.
```
λ ~ → nix-env -iA dhall -f https://github.com/dhall-lang/dhall-haskell/archive/bebfbf2a5af220048dabd28b0776b1e2d1b6c6ca.tar.gz
unpacking 'https://github.com/dhall-lang/dhall-haskell/archive/bebfbf2a5af220048dabd28b0776b1e2d1b6c6ca.tar.gz'...
unpacking 'https://github.com/NixOS/nixpkgs/archive/925aac04f4ca58aceb83beef18cb7dae0715421b.tar.gz'...
copying path '/nix/store/937b1ps5v3ixg20s7wird5c5szlmw8pa-musl-1.1.19' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/7fm29lr224zhp6cwqg1in6qbf1rnp53d-base-orphans-0.7-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/x0n04z9q7gpp380iv3ld16g43ng4q246-apr-1.6.3' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/nf0zwz2il3hgcz5i7bgri7jb3wi1cjf5-attr-2.4.47' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/h0776npra2dhhrm4x9n1z72876p1qmsc-bash-4.4-p23' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/yz6xvr3kniw6jinkdxamg8q3z17lvlmb-acl-2.2.52' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/mlm66dihgvydzq993fvkgc114l17pdm2-brotli-1.0.4-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/fn1l45mjqvn1qlm2qqj1rglmi8xv2lmn-busybox-1.28.4' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/3ggr7zhyysa4b4i4dd0z1z75jqhmhdx9-byteable-0.1.1-data' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/r707d7733qmajvbzqgd1zm88bcm1a8am-bzip2-1.0.6.0.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/fgp7173sinfn2g5d68nwmlapqkzfzwwv-colour-2.3.4-data' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/cp0w9qqw2wlmxzfc4zqc2va83cdin4p9-bzip2-1.0.6.0.1-bin' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/jgd175yqgpra6g3pcnpvj9cs450722ak-coreutils-8.29' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/f36nnz6dhwk9907fj94vhwxbq2r45l76-expand-response-params' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/92dnp1bh9960caimv3wi21cwrif52vgq-cvs-1.12.13' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/9q28h82f68m81p5ri31yyq7qy2hvdpan-diffutils-3.6' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/jw126dvsmyq9zz8bhhvlfwvyw4irg7p4-expat-2.2.5' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/r3vd55d9s8hpivlbqdiflqrs8fb1jyks-findutils-4.6.0' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/xd8k21hr68q9b0j9ifh4rg47am4hfyc7-gawk-4.2.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/nlb2s2xvjy42xg64szwq2pgjkhh7168j-gcc-7.3.0-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/y8xp4iabwbwrw87l2rxlzp9ydgl5zpin-gdbm-1.14.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/95xf1361akhvysb8sjplrd28q6qiwq9y-db-4.8.30' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/wmq67iwqnzp18xghjg2kn22nskvz3q3m-db-5.3.28' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/v9mp6yky038h7dgdm7zb75mibrr4kq77-gettext-0.19.8.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/q0g2pp86wqlk8diyridand3hifk18z51-ghc-8.4.3-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/j7fpsf8xc0faxgbyxm56ddvybhz4mjck-gnumake-4.2.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/254rgj92dhkyg7sydb7al65gflnyjd7b-gmp-6.1.2' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/apj959asx87nbda6nh2w63vqigq0mbdh-Glob-0.9.2-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/8gqz0bx5xk16csgvv6m4qzmxmndinb6n-StateVar-1.1.1.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/y4yrn3wym0g9ilsdnd4cpa2v9lwcqidv-base-compat-0.10.4-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/hp92rj472rfr6r3dqmipdikx9s9vlkr4-basement-0.0.7-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/4q62zxzcnl4nfg2yf6lnv4irc7kgfks2-blaze-builder-0.4.1.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/wcfjm660zp7n94jnx0r4jwmbjcgcvgvz-byteable-0.1.1-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/qkvpyjk96zs9g2mgccy86nzkjxvvg6xa-call-stack-0.1.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/x7bcbpdh5r72589ska2f2hz4pxvfkgni-cereal-0.5.5.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/c96ccssdzc8xlww83v8mw8wx6b272q2k-colour-2.3.4-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/wq241g5p1al4nic5k5656iyccqy5n59f-contravariant-1.4.1-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/blmafy0mgp63w7nmf0jlikpxanfvpd47-ansi-terminal-0.8.0.4-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/1s802y25ixfcmmr4ix3nrhpka9ah565w-data-default-class-0.1.2.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/b05s5kb12yisl3swfcl2qjq5qss5jar1-ansi-wl-pprint-0.6.8.2-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/z67if6i7fvalyhbvp6ljyq52jbpyg6b0-cookie-0.4.4-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/ylaprbzzibkdlrair8d6baga9v01x786-dlist-0.8.0.4-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/xyh3px9288glc1gl5lg27xbsyy8cjc6m-exceptions-0.10.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/yhjvkb9anlzszbddp4g4wvdzfywcm9wn-foundation-0.0.20-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/wbgg70ij5vjidlj93z07x9bcrgl0i78a-gmp-6.1.2-dev' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/s2b3lp72v7n7yb4m5wcifnz4awshw8w8-gnused-4.5' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/vy9kmk6g4b7gczbn9bkhg3ivpmiax87q-gnutar-1.30' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/r2rfrf2in8bk6jba6wi1xfh957r72yij-gzip-1.9' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/rlxf0k6g3vh700hxpm3l7ijz9n9ydp3n-hashable-1.2.7.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/5xrphxb0zn2aqbazbwmsidlp9zn8d5dw-hopenssl-2.2.1-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/hbkhm4ch2qpf5fm6x5dvlyk2n5fq630k-async-2.2.1-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/rn8qwsavq3hvlp3wvfjfsf76l50paljw-case-insensitive-1.2.0.11-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/7jjgczzkb4baaickh0yy67f3h609aqfx-hourglass-0.2.11-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/d5f9xakq7ydlajq06fac1lqjfdzk9afh-http-types-0.12.1-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/cbdhvhlayvn10qm6kmk5rvip47jk2bym-asn1-types-0.3.2-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/l54fxkjiig6cr4dih9fnsmb7s7xsp5z4-integer-logarithms-1.0.2.1-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/qihj376m9a10blm513ggd7rdi7c744jr-asn1-encoding-0.9.5-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/lkhnqmpv7hy4jbfc85a0pj4pbz0bl9i9-libatomic_ops-7.6.4' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/7byp8idasfbx5n0m5hwd7a8c9i3fww5s-asn1-parse-0.9.4-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/5hm133hq8jf46vpy922lxyiij3xmgfhw-boehm-gc-7.6.6' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/vd4vwjsnqccvn3shsqin26a62391vvv1-libffi-3.2.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/3rnai60vdwm4aac0n5ylqk7kk19h5zf9-libkrb5-1.15.2' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/3zvja3haf2d68hi77h49i51i1rl5k1ha-libffi-3.2.1-dev' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/85j43as9p97ckx3d7c32h5yb4bdg77pd-libseccomp-2.3.3-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/f4bqahky1hk650p8122fdyqznn10aqx2-libsodium-1.0.16' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/9bdd1hc48p8lb6fyby16qq8yksrl4c6j-libtool-2.4.6-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/mcqmy5krh027170f6jhq10fr5vvcxc4p-libyaml-0.1.7' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/xkkk9c58nn049f2y1nsvn8f32bjywbq9-linux-headers-4.15' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/0s8sijq9gmsmig66lk3mq63yaa40i88k-memory-0.14.16-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/76zip7pzcpjjxjgvc443bw0z3w63ap44-mime-types-0.1.0.8-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/45y0si9h33axm01879zqj7sa6zkmz3zx-cryptonite-0.25-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/cmmzc88f9ryhyyw24swvzmpj37i8rdrk-musl-1.1.19-dev' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/1xwbnc903gymfi99zpvj8mdp5601yqz6-ncurses-6.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/89lj7wjp81pbg4wv2yf8fwm4p5dzq27b-musl-iconv-1.1.19' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/v0gd8z0icpqih7f21srhink04ixkp03g-libedit-20180525-3.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/ry4v58b0ga6v8f2dsi9q49j1nvaparwg-network-2.6.3.6-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/597rx3bfv6f1rs5gjjsh9bqyilbi0jp6-network-uri-2.6.1.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/iayifs90rkhm372hgcyg0r29ynmy9da4-nghttp2-1.32.0-lib' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/raqghanamdjmzpmabjys326wk6xyam0i-nix-2.0.4-man' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/8fl484flaj4rwzwpd5wh4icy1c11lrsi-old-locale-1.0.0.7-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/wd5fgydiwjwnjcimpdg0vja2kw5sy77i-openssl-1.0.2o' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/3rymk7hzqrvn43ni5gb0hsph4hkcj2ff-optparse-applicative-0.14.2.0-doc' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/bnmhvqpsk52vrvz5ak0a1sv315pgzfkk-cyrus-sasl-2.1.26' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/32cblzrdvjf4bs1sdm4xip5hi6y3qzqg-parallel-3.2.1.1-doc' from 'https://cache.dhall-lang.org'...
...
...
```

**Comment by Gabriel439** [comment] 2019-01-21 16:19
@PierreR: Are you using OS X or Linux?

**Comment by PierreR** [comment] 2019-01-21 16:34
I am using Linux (nixos)

**Comment by Gabriel439** [comment] 2019-02-12 06:22
@PierreR: So I can help you fix this error:

```
./dhall-lang/tests/import/data/fieldOrder/: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

This is because of the switch to use `git` submodules to fetch the `dhall-lang` repository.  If you first do:

```
$ git submodule init
$ git submodule update
```

... then I believe the `nix-build` should work

**Comment by PierreR** [comment] 2019-02-12 09:48
Ideally I would like to do this without cloning the repo:
```
nix-env -iA dhall -f https://github.com/dhall-lang/dhall-haskell/archive/bebfbf2a5af220048dabd28b0776b1e2d1b6c6ca.tar.gz
```
It is possible in any way ?

**Comment by PierreR** [comment] 2019-02-12 10:00
@Gabriel439 If it is not possible, that's not a big deal. I can keep using my custom derivation. Please feel free to close this issue if that's the case.

**Comment by Gabriel439** [comment] 2019-02-16 00:16
@PierreR: Actually, I think I better understand what is going on now and I think there is a simple solution for what you want.

First, the simple solution: `nix-env` allows you install pre-built artifacts from any available cache by specifying the `/nix/store` path to install, like this:

```bash
$ nix-env -i /nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1
```

Once this pull request is merged:

https://github.com/dhall-lang/dhall-haskell/pull/821

... then you can obtain the path to install by visiting:

https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest

... and then clicking the "Help" button in the bottom right, which will give you the exact `nix-env` command to run to install the pre-built package.

Second, the reason `nix-env` was not downloading a pre-built binary was because the archive downloaded from GitHub is not the same as a local source checkout.  Specifically, the archive does *not* contain the `dhall-lang` submodule.

Because the `dhall` subdirectory in the source contained in the archive is not identical to a local checkout then `nix-env` has to rebuild the `dhall` package.  This is why you got a cache miss for `dhall` instead of downloading a pre-built statically linked executable from `cache.dhall-lang.org`.

This also explains why you download a large number of dependencies when you try to install Dhall from the downloaded archive.  If you look carefully at the list of downloads, they are all downloads for *build-time* dependencies (i.e. `musl`, `nixpkgs`, etc.), not run-time dependencies.  This is expected behavior because you have to rebuild the `dhall` package locally due to the cache miss.

However, rather than fix that I think the right solution is to just use `nix-env` to install a `/nix/store` path from `cache.dhall-lang.org` as noted above.  That guarantees that it's going to be a cache hit.

**Closed** 2019-02-22 15:33 UTC

**Comment by PierreR** [comment] 2019-02-22 22:34
I believe there is something wrong with the indication ?

```
λ  ~ → nix-env -i "$(https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest/api/get-info | jq -r .outPath)"
zsh: no such file or directory: https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest/api/get-info
```
or
```
λ  ~ → nix-env -i /nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1                                                 
replacing old 'dhall-1.20.1'
installing 'dhall-1.20.1'
don't know how to build these paths:
  /nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1
error: path '/nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1' does not exist and cannot be created
```

**Comment by ocharles** [comment] 2019-02-22 22:59
For the first, you are missing a call to `curl` on the URL.
```
nix-env -i "$(curl -L https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest/api/get-info | jq -r .outPath)"
```

For both you will need to have `http://hydra.dhall-lang.org` set up as an available binary substitute.

**Comment by PierreR** [comment] 2019-02-22 23:14
Thanks ! I know how to set up `http://hydra.dhall-lang.org` as a binary cache but I am not familiar with binary substitute (I am using nixos). How can I know the associated binaryCachePublicKeys ?

**Comment by ocharles** [comment] 2019-02-23 08:35
A binary cache is the same thing as a binary substitute :) Just different names. I'm not sure about keys - I'm not even sure if we're signing anything.

**Comment by PierreR** [comment] 2019-02-23 10:16
I still have the same error actually. My second attempt was using channel but the error is the same.

I don't know why it does not want to write the path on the store. Maybe I need to configure something to allow insecure cache ?

```
→ nix-env -i /nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1 --substituters http://hydra.dhall-lang.org  
replacing old 'dhall-1.20.1'
installing 'dhall-1.20.1'
these paths will be fetched (0.00 MiB download, 18.27 MiB unpacked):
  /nix/store/937b1ps5v3ixg20s7wird5c5szlmw8pa-musl-1.1.19
  /nix/store/i9b8pkiaj96xx687i1vq964swr8s56jh-ncurses-6.1
  /nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1
warning: substituter 'http://hydra.dhall-lang.org' does not have a valid signature for path '/nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1'
error: path '/nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1' does not exist and cannot be created

λ ~ → nix-env -i dhall        
replacing old 'dhall-1.20.1'
installing 'dhall-1.20.1'
error: path '/nix/store/v9v8inqmx4dfgsw5k1pwrb2336sqp2k1-dhall-1.20.1' does not exist and cannot be created
```

**Comment by Gabriel439** [comment] 2019-02-23 16:50
@PierreR: I have a pull request up with instructions on how to use `cache.dhall-lang.org`:

https://github.com/dhall-lang/dhall-haskell/pull/827

Check that out and see if that works for you

**Comment by PierreR** [comment] 2019-02-24 20:18
It works nicely. Thanks !
