### ISSUE TITLE
(Debug) logging

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1328] opened 2019-09-18 17:55 UTC
Sometimes I'd like to see what's happening when `dhall` processes an expression:

* How much time is spent on type-checking, normalizing, pretty-printing?
* Which imports were found in which cache, or had to be downloaded?

Logging would be very useful to answer such questions!

**Comment by Gabriel439** [comment] 2019-09-19 04:13
This information is available without any code changes!

For example, you can debug performance using a profiled build and you can debug file reads/writes using `strace` (Linux) or `dtruss` (OS X).  For example:

```bash
$ sudo dtruss -t open dhall <<< 'https://prelude.dhall-lang.org/package.dhall'
…
dtrace: 497 dynamic variable drops with non-empty dirty list
open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE3819C80)		 = 3 0
open("/Users/gabriel/.nix-profile/bin/dhall\0", 0x8004, 0x5DA93ADE)		 = 4 0
open("/dev/random\0", 0x20004, 0x1B6)		 = 5 0
open("/dev/urandom\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/12207ee950e7c2142be5923f76d00263e536b71d96cb9c190d7743c1679501ddeb0a\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/1220b8d20ab3216083622ae371fb42a6732bc67bb2d66e84989c8ddba7556a336cf7\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/122074c3822b98b9d37f9f820af8e1a7ee790bcfac03050eabd45af4a255fb93e026\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/1220eb464566d3192dd16ce915a9bd874aaaad612d5c69beb356e5b7d2e0c4949dcf\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/1220108be3af5ebd465f7091039f2216c433e65ae5d25556a9a71786dd84d33ef49a\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/122007cc274220c8bdb2c1a0c2d00d90bc1447e73e0ad2e1d72b89773e923f77e71e\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/12208421079b9698b765774455b63f4561f7bfa1506ed3fa39cfb5c34a4cd1c9df4b\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/122036a366af67a3c26cd5d196e095d3023f18953c5b5db3a03956fa554609e5442a\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/122034a613c89df3f314c606a813f592d1a09fedb3e5f5e63fcc0ae9c88245e8bdad\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/12200a0ad9f649aed94c2680491efb384925b5b2bb5b353f1b8a7eb134955c1ffe45\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall/12206aed7e845c29bc528ced19b99f860c5bcd50f24a1394631fe66f751999f85361\0", 0x20004, 0x1B6)		 = 5 0
open("/Users/gabriel/.cache/dhall-haskell/1220771c7131fc87e13eb18f770a27c59f9418879f7e230ba2a50e46f4461f43ec69\0", 0x20004, 0x1B6)		 = 5 0

```

**Comment by jneira** [comment] 2019-09-19 08:38
I think debug can be useful in general, it helps to trace the "steps", including external actions like http requests or changes in files, or to discover the cause of bugs or unexpected behaviour.

But it adds complexity and a lot of locs...

I think we could choose a logging library and start to trace incremantally.

**Comment by Gabriel439** [comment] 2021-06-16 22:32
Closing as I believe this is handled by existing profiling/tracing tools

**Closed by Gabriel439** 2021-06-16 22:32 UTC
Labels: enhancement
