### ISSUE TITLE
Slightly confusing error that could be better

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-haskell#176] opened 2017-11-06 10:38 UTC
Given

```
$ echo "{x:Bool}" > ty
$ echo "let t = ./ty in \(x:t) -> x.x" | dhall
```

Dhall replies 

```
Use "dhall --explain" for detailed errors

t : Type
x : t

Error: Not a record

x.x
```

I'd think the problem is not that t isn't a record but that determining this is now out-of-phase.

Could the error message be more descriptive here?

(You get this kind of a situation when your  type lives in a different url than your function and you can't simply use a relative path to access the type. It would be nice to be able to bind the type to a shorter name.)

**Comment by Gabriel439** [comment] 2017-11-06 18:06
The problem isn't the use of an import but rather the use of a `let` binding.  Even if you resolved ahead of time you would still get the same error:

```
$ dhall
let t = { x : Bool } in λ(x : t) → x.x 
^D
Use "dhall --explain" for detailed errors

t : Type
x : t

Error: Not a record

x.x

(stdin):1:36

```

If you use the import directly for the type annotation then the problem disappears

```
λ(x : ./ty) → x.x
```

You can always shorten a long import name by creating a local file with a shorter name that imports the longer name.  For example:

```
$ cat ./t
http://example.com/someLongImportName
```

**Comment by aleator** [comment] 2017-11-18 13:04
Ah, sorry about my confusion, however, I still think that the error emitted in this case could be better. Is there any case where binding a type in let would be useful? If not, then the error could be emitted there.

**Comment by Gabriel439** [comment] 2017-11-18 17:06
`let`-binding a type is useful when you wan to reduce duplication within a larger type

For example:

```haskell
$ dhall <<< 'λ(x : let t = Bool in { foo : t, bar : t }) → x.foo'
∀(x : { bar : Bool, foo : Bool }) → Bool

λ(x : { bar : Bool, foo : Bool }) → x.foo
```

Also, this is valid, too, although less useful:

```haskell
$ dhall <<< 'let t = Bool in λ(x : t) → x'
∀(x : Bool) → Bool

λ(x : Bool) → x
```

**Comment by aleator** [comment] 2017-12-05 12:38
I see.

I think you can close this issue, but I still think that documentation or the tutorial might benefit from mentioning this limitation.

**Comment by Gabriel439** [comment] 2017-12-17 01:07
The Dhall tutorial has an [FAQ section](https://hackage.haskell.org/package/dhall-1.8.2/docs/Dhall-Tutorial.html#g:53) which mentions this limitation and the work-around

**Comment by Gabriel439** [comment] 2018-01-19 03:44
This is now fixed by https://github.com/dhall-lang/dhall-lang/commit/4bbd897df48e708068f7107c88a82b7c2e0c8456

The next release of `dhall` will have support for type synonyms.  This means that your original example code works on `master`:

```
dhall <<< 'let t = { x : Bool } in λ(x : t) → x.x '
∀(x : { x : Bool }) → Bool

λ(x : { x : Bool }) → x.x
```

**Closed by Gabriel439** 2018-01-19 03:44 UTC
