### ISSUE TITLE
`dhall format` adds newlines on comments within let-bindings

### ISSUE THREAD

**Issue by AJChapman** [dhall-lang/dhall-haskell#1413] opened 2019-10-11 01:22 UTC
I have been using `dhall format` in an editor hook to format my dhall files, but it is erasing my comments! I would expect this with `dhall normalize`, but surely `dhall format` is supposed to leave the comments? Using dhall version 1.26.1:

    $ dhall format <<< '"hello" -- hello'
    "hello"

Also inline comments:

    $ dhall format <<< '{ foo: 1 {- test -}, bar: 2 }'
    { foo : 1, bar : 2 }

Sometimes inline comments have extra newlines added instead of being erased:

    $ dhall format <<< 'let foo =
    {- test -}
    "hello"
    in foo'

Outputs:

    let foo =
    
        {- test -}
          "hello"

    in  foo

Piping the output back to `dhall format` results in more newlines:

    $ dhall format <<< 'let foo =
    {- test -}
    "hello"
    in foo' | dhall format

Outputs:

    let foo =
    
    
        {- test -}
          "hello"
    
    in  foo

It seems comments are preserved when they are at the beginning of the file, on their own line:

    dhall format <<< '{- test -}
    "hello"'

Correctly outputs:

    {- test -}
    "hello"

**Comment by sjakobi** [comment] 2019-10-11 01:31
Thanks for the report. This is mostly a duplicate of https://github.com/dhall-lang/dhall-haskell/issues/145, but the addition of newlines on comments within let-bindings is a bug that deserves its own ticket.

In general, `dhall format` should be idempotent. That is, given some expression `x`, we want the outputs of `echo x | dhall format` and `echo x | dhall format | dhall format` to be the same.

**Closed** 2019-10-15 15:01 UTC
Labels: bug, formatting
