### ISSUE TITLE
dhallToNix is quite a difficult nixpkgs citizen

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1624] opened 2020-01-08 14:33 UTC
It is a bit ironic but `dhallToNix` is quite difficult to build with nixpkgs.
You will need to make something like this with the current nixpkgs master commit ref:
```
unstable = rec {
    hnix = pkgs-unstable.haskellPackages.hnix.override { prettyprinter = pkgs- unstable.haskellPackages.prettyprinter_1_5_1;};
    dhall = pkgs-unstable.haskellPackages.dhall_1_28_0;
    dhall-nix = pkgs-unstable.dhall-nix.override { inherit dhall hnix;};
    dhallToNix = pkgs-unstable.dhallToNix.override {inherit dhall-nix;};
}
```
Also I am pretty sure it does not build with the stable branch (and getting the stable branch to build it correctly would require at least the same level of complexity).

That said I understand `dhallToNix` is not a priority (I am actually pondering about replacing my dhall config associated with nix scripts with some nix files instead)

Cheers,

**Comment by Gabriel439** [comment] 2020-01-08 14:37
@PierreR: This is more likely an issue with Nixpkgs.  The latest versions of all the relevant `dhall*` packages build together.  There's nothing I can really do on my end to fix things

**Comment by sjakobi** [comment] 2020-01-08 14:40
I think part of the problem is that the latest `hnix` release isn't compatible with the `prettyprinter` version that `dhall` requires.

I hope that `hnix` can get a new release soon, but it [seems a bit stuck](https://github.com/haskell-nix/hnix/issues/524).

**Comment by PierreR** [comment] 2020-01-08 15:15
@Gabriel439 Well I know dhall-nix is ok. It is just a bit of a shame that `dhallToNix` does not work in nixpkgs. It has been advertised as one possible good use case for dhall-nix  ;-)

@sjakobi Thanks for the link. It gives some interesting context.

**Comment by Profpatsch** [comment] 2020-01-19 00:00
I wonder if we can maybe use the static release binaries if the Haskell snapshot is broken so often. That’s what I do in my (various) reimplementation(s) of `dhallToNix` anyway. Justin has a repo that packages them: https://github.com/justinwoo/easy-dhall-nix

**Comment by Gabriel439** [comment] 2020-01-19 03:46
@Profpatsch: Regarding moving them outside of Nixpkgs: this repository already provides a `default.nix` expression you can import and use to build all of the various `dhall*` executables.  For example, that's how the `dhall-lang.org` website obtains the code used to power the website:

https://github.com/dhall-lang/dhall-lang/blob/fda6d22ac4e4977bef6a7559fea22a01d75118c3/nixops/logical.nix#L186-L201

... but you could use the same trick to obtain everything else built by this repository, including `dhall-to-nix`

**Comment by Gabriel439** [comment] 2021-06-16 23:02
Closing this as there isn't much we can do on our end other than to ensure that the latest versions of the packages build together

**Closed by Gabriel439** 2021-06-16 23:02 UTC
Labels: build
