### ISSUE TITLE
`yaml-to-dhall` is erratic with unions

### ISSUE THREAD

**Issue by vvv** [dhall-lang/dhall-haskell#1197] opened 2019-08-03 21:27 UTC
```sh
$ cat U.dhall
< x : { x : Optional Natural } | y : { y : Optional Natural } >
```

Valid YAML, but inconsistent use of quoting:
```sh
$ dhall-to-yaml <<<'let U = ./U.dhall in U.x { x = Some 1 }'
x: 1
$ dhall-to-yaml <<<'let U = ./U.dhall in U.y { y = Some 1 }'
'y': 1
```

Correct:
```sh
$ echo 'x: 1' | yaml-to-dhall ./U.dhall
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x { x = Some 1 }
```

Wrong:
```sh
$ echo 'y: 1' | yaml-to-dhall ./U.dhall
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x
{ x = None Natural }
$ echo "'y': 1" | yaml-to-dhall ./U.dhall
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x
{ x = None Natural }
```

**Comment by vvv** [comment] 2019-08-03 21:28
```sh
$ yaml-to-dhall --version ''
1.4.0
```

**Comment by vvv** [comment] 2019-08-03 21:35
Similar behaviour is observed with `json-to-dhall`:
```sh
$ echo '{"x":1}' | json-to-dhall ./U.dhall 
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x { x = Some 1 }
$ echo '{"y":1}' | json-to-dhall ./U.dhall 
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x
{ x = None Natural }
```

**Comment by Gabriel439** [comment] 2019-08-03 21:39
The reason for the inconsistency in `dhall-to-yaml`'s quoting is because YAML interprets an unquoted `y` as `true`, not the string/key 'y'.  So `dhall-to-yaml` is actually behaving correctly here and protecting against the generated YAML being misinterpreted.

This is also the same reason why this example fails:

```bash
$ echo 'y: 1' | yaml-to-dhall ./U.dhall
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x
{ x = None Natural }
```

Because `y: 1` is not what you think it is!  It's essentially the YAML version of `[ { mapKey = True, mapValue = 1 } ]`.

However, you are right to be surprised about this behavior:

```bash
$ echo "'y': 1" | yaml-to-dhall ./U.dhall
< x : { x : Optional Natural } | y : { y : Optional Natural } >.x
{ x = None Natural }
```

The root cause behind that is because `yaml-to-dhall` does not have the `--records-strict` flag on by default.  I actually found this behavior surprising, too, so I just fixed it yesterday in this pull request:

https://github.com/dhall-lang/dhall-haskell/pull/1181

... and indeed on `master` it gives the behavior you expected:

```bash
$ yaml-to-dhall '< x : { x : Optional Natural } | y : { y : Optional Natural } >' <<< "'y': 1"
< x : { x : Optional Natural } | y : { y : Optional Natural } >.y { y = Some 1 }
```

**Comment by sjakobi** [comment] 2019-08-28 22:17
According to https://stackoverflow.com/a/42284910/1013393 only `true`, `True`, `TRUE`, `false`, `False`, and `FALSE` should be parsed as bools in YAML1.2. YAML1.1 bools like `y` or `off` should now be interpreted as strings.

**Comment by Gabriel439** [comment] 2019-08-29 15:54
@sjakobi: Maybe that will be fixed by #1248

**Comment by sjakobi** [comment] 2019-10-07 14:42
This was indeed fixed by #1248! Thanks @vijayphoenix! :)

It might be a good idea to add regression tests, so we can ensure that this keeps working even with the `aeson-yaml` flag that I understand @patrickmn will introduce.

**Comment by patrickmn** [comment] 2019-10-09 17:13
Agreed.

I plan to do a PR no later than the weekend.

**Comment by patrickmn** [comment] 2019-10-15 10:49
This slipped my mind when I was adding the list of special strings (aeson-yaml will quote 'y'/'n'/'on'/'off'). 

Will submit a fix and regression test soon.

---

FYI this seems like a general issue:

https://github.com/go-yaml/yaml/issues/214

https://github.com/kubernetes/kubernetes/issues/34146#issuecomment-527974153

(Also, perhaps expectedly, when I remove the quoting of 'yes'/'no', my test to assert that libyaml decodes the original input fails.)

..but it seems reasonable to expect the Dhall user not to feed "yes" to Kubernetes.

**Closed** 2019-10-15 13:18 UTC
Labels: json/yaml
