### ISSUE TITLE
Confusing "Error: not an equivalence" message

### ISSUE THREAD

**Issue by Xe** [dhall-lang/dhall-haskell#1927] opened 2020-07-16 20:28 UTC
I'm getting a weird error message when trying to build some Kubernetes manifests. See my errors [here](https://drone.tulpa.dev/cadey/kubermemes/21/1/2).

What am I doing wrong?

**Comment by sjakobi** [comment] 2020-07-16 20:41
Strange! It reminds me of https://github.com/dhall-lang/dhall-lang/issues/783 but it's not obviously related.

How can we reproduce this? Are you using the latest versions of tools?

**Comment by Xe** [comment] 2020-07-16 20:44
I am using dhall-yaml version 1.2.0 and dhall version 1.33.1:

```console
$ dhall-to-yaml-ng --version
1.2.0

$ dhall --version
1.33.1
```

**Comment by sjakobi** [comment] 2020-07-16 20:59
Thanks! Could you give us instructions that we can reproduce the issue with?

And do you happen to use an old `Prelude` version? That might be a hint at https://github.com/dhall-lang/dhall-lang/issues/783…

**Comment by Xe** [comment] 2020-07-16 21:12
With Nix:

1. clone https://tulpa.dev/cadey/kubermemes somewhere on your disk
2. run `nix-shell` in the directory
3. `$ cd k8s`
4. `dhall-to-yaml-ng --omit-empty --documents --file allApps.dhall`

Without Nix:

1. clone https://tulpa.dev/cadey/kubermemes somewhere on your disk
2. `docker build .`

**Comment by sjakobi** [comment] 2020-07-16 21:33
I'm getting a different error when I follow the Nix instructions:

```
$ dhall-to-yaml-ng --omit-empty --documents --file allApps.dhall


↳ ./apps/hlang.dhall
  ↳ ./app/make.dhall
    ↳ ./http/deployment.dhall

Error: Expression doesn't match annotation

{ name : - Optional …
         + Text
, …
}

46│                        kubernetes.ObjectMeta::{
47│             , name = config.name
48│             , labels = Some (selector config.name)
49│             }

/home/simon/src/kubermemes/k8s/http/deployment.dhall:46:24

7│                  ../http/deployment.dhall

/home/simon/src/kubermemes/k8s/app/make.dhall:7:18
```

I'm wondering whether your `k8s/Prelude.dhall` could be a problem:

```
$ cat k8s/Prelude.dhall 
https://prelude.dhall-lang.org/package.dhall
```

This is an "unstable" import – it's updated with each Dhall standard release.

I suspect that in `dhall`'s "semi-semantic" cache (usually in `~/.cache/dhall-haskell/`) you've cached an old buggy Prelude version. I don't know why it would suddenly cause problems though… Did you recently update your `dhall` and `dhall-to-yaml-ng` versions?

@Gabriel439 does something like this seem plausible?

@Xe What you can try is pin the Prelude version, e.g. `https://prelude.dhall-lang.org/v17.0.0/package.dhall`. That URL is stable, so you shouldn't run into stale cache issues.

**Comment by Gabriel439** [comment] 2020-07-17 01:30
I also was not able to reproduce the problem:

```bash
[nix-shell:~/proj/kubermemes/k8s]$ dhall hash --file ./Prelude.dhall 
sha256:10db3c919c25e9046833df897a8ffe2701dc390fa0893d958c3430524be5a43e
```

It's good to pin to a specific prelude version, but using the latest Prelude release would not explain the issue.

I don't think the semi-semantic cache could be interfering here since it's not used to resolve the `missing` import.

The easiest way to know for sure what the problem is would be to reproduce the problem while the `--explain` flag is enabled.  That will likely give a big clue to what's going on.

**Comment by sjakobi** [comment] 2021-01-16 19:17
Closing since we don't have sufficient information to make any progress here.

**Closed by sjakobi** 2021-01-16 19:17 UTC
