### ISSUE TITLE
Strange error when using record completion on a bound variable

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#2102] opened 2020-11-25 20:53 UTC
```dhall
\(x : { Type : Type, default : {} }) -> x::{ um = "hi" }
```

Gives

```
Error: Expression doesn't match annotation

- ….…
+ { … : … } (a record type)

2│     x::{ um = "hi" }
```

But this is very difficult to understand. 

Note that

```
let x : { Type : Type, default : {} } =
    { Type = { um : Text }, default = {=} } 
    
in x::{ um = "hi" }
```

does work, which makes me think `::` doesn't work on abstracted variables. I think the problem is because it is desugaring to literally `x.Type`, but `x` is a record, not a record literal, and dot-syntax is not supported here (https://github.com/dhall-lang/dhall-lang/issues/1079)

**Comment by Gabriel439** [comment] 2020-11-25 21:58
If you add `--explain` it provides a bit more detail as what is going on:

```
dhall --explain                        
\(x : { Type : Type, default : {} }) -> x::{ um = "hi" }
^D

x : { Type : Type, default : {} }

Error: Expression doesn't match annotation

- ….…
+ { … : … } (a record type)

…

You or the interpreter annotated this expression:

↳ x.default ⫽ { um = "hi" }

... with this type or kind:

↳ x.Type

... but the inferred type or kind of the expression is actually:

↳ { um : Text }

────────────────────────────────────────────────────────────────────────────────

1│                                         x::{ um = "hi" }

(input):1:41
```

It's a type error because:

```dhall
\(x : { Type : Type, default : {} }) -> x::{ um = "hi" }
```

… desugars to:

```dhall
\(x : { Type : Type, default : {} }) -> (x.default ⫽ { um = "hi" }) : x.Type
```

… and the type-checker has no way of knowing what type `x.Type` is in advance since `x` is abstract.

Just to clarify: the `x.Type` field access is well-typed (since the type-checker knows from the context that `x` is a record with a field named `Type`).  The issue is that `x.Type` could end up being `Bool` or `Text`; the type-checker can't guarantee that `x.Type` will be a record type, let alone the specific record of type `{ um : Text }`

**Comment by ocharles** [comment] 2020-11-25 22:12
Ah yea, that all makes sense - thanks.

**Comment by Gabriel439** [comment] 2020-11-25 22:15
You're welcome!  I'll close this, then

**Closed by Gabriel439** 2020-11-25 22:15 UTC
