### ISSUE TITLE
Improve performance by caching

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-haskell#362] opened 2018-04-19 11:43 UTC
I have a rather large dhall configuration and it is really taking far too long to process. I believe an order of magnitude improvement could be had just by caching the imports. 

```
> echo "./MySetup" | fsatrace r trace -- dhall
... Output clipped
> wc -l trace
550
>sort trace|uniq -c |wc -l
37
> dhall version
1.12.0
```

For the record, there are 68 files in my directory, most of them small dhall files that are eventually collected in the huge list above.

I thought that dhall already had some caching in place?

**Comment by Gabriel439** [comment] 2018-04-19 15:12
Dhall does have caching in place, so this seems like a bug.  Let me see if I can reproduce this issue locally

**Comment by aleator** [comment] 2018-04-20 06:39
Let me know if you want the blob of files I used.

**Comment by Gabriel439** [comment] 2018-04-23 17:13
@aleator: I think the main thing that would help if you have time is a minimal reproducing example of a file being imported twice

**Comment by aleator** [comment] 2018-04-27 08:05
I'll try to cook one up, but I probably won't manage to have time until next week.

**Comment by Gabriel439** [comment] 2018-04-30 04:09
Also, it might not be necessary.  I'm in the process of formalizing the import semantics and updating the Haskell implementation to match the standard semantics so the problem might disappear after that.  I'll let you know when that is complete so that you can check again if the problem still persists.

**Comment by sellout** [comment] 2018-05-14 17:51
I haven’t yet been able to run fsatrace (on a Mac), but if this is the case, it would explain some of the slow performance we’ve been seeing. We have a couple files that take a few seconds to normalize on their own, but when referenced by other files (that reference those slower files indirectly through a few different imports), it extends to minutes.

**Comment by sellout** [comment] 2018-05-15 21:15
I’m digging into this now. I’ve identified two bugs and fixed one of them so far, but I feel like there is a third one lingering. Should have a PR soon.

**Comment by sellout** [comment] 2018-05-15 21:57
Ok, so the second bug that I identified is maybe a bit tricky. `FilePath.normalize` doesn’t eliminate `..` from paths, so you can end up importing the same file multiple times based on where you imported it _from_. `System.Directory.canonicalizePath` fixes this, but it actually looks at the filesystem, so uses `IO`. We could simply remove `/[^/]+/\.\.` (i.e., the `..` and the next directory up), but that wouldn’t behave properly around symlinks (which is why `canonicalizePath` uses `IO`.

In my simple testing, I had a dhall file trigger 532 imports. Fixing the first bug (imports containing imports don’t get cached) brought that down to 240, and if I manually canonicalize `..`, I get down to 82.

**Comment by Gabriel439** [comment] 2018-05-15 22:42
@sellout: If something is hard to fix, it's fine to defer the harder fixes for later.  Keep in mind that I'm still in the process of updating the import code to match the standard and that actually simplifies the logic a lot and fixes a lot of canonicalization issues, too, and that might actually fix these harder bugs

**Comment by sellout** [comment] 2018-05-15 23:36
Yeah, this issue is more of a jumping off point for me to try to improve performance, so I’m jumping around to a few different places seeing what I can do. (And also just an excuse to finally contribute to Dhall proper.) So far, fewer imports hasn’t had much of an impact, so getting the path normalization fixed or whatever isn’t a priority for me.

One thing I thought might help is caching _normalized_ imports rather than only normalizing the full expression at the end. However, when I added `Dhall.Core.normalize` before caching, I get a “Handlers should have the same output type” error that doesn’t occur without normalization there (but none of the unit tests break). Any idea why that would be happening? My naïve assumption was that normalization should work anywhere (as long as the Expr is well-typed).

**Comment by Gabriel439** [comment] 2018-05-16 01:00
The last time I checked, the number one thing that will improve performance is fixing the parser to use `attoparsec` to lex the input.  See: #108 

Normalizing something shouldn't change its type (it's one of the four soundness rules for Dhall), so that latter issue sounds like a bug

**Comment by Gabriel439** [comment] 2018-05-16 01:05
@sellout: Also, if you are going to make more changes to the import system, I highly recommend reading the standardized semantics for imports here:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#import-resolution

That's where the import system is going and it's simpler than the current implementation

**Comment by sellout** [comment] 2018-05-16 03:17
If parsing were the (only) problem, I would have expected cutting the imports in half to have had a significant impact on my runtime. Also, I just benchmarked, and I seem to have pretty different hotspots:
```
	Tue May 15 21:10 2018 Time and Allocation Profiling Report  (Final)

	   dhall +RTS -p -RTS

	total time  =       44.25 secs   (44249 ticks @ 1000 us, 1 processor)
	total alloc = 48,733,132,592 bytes  (excludes profiling overheads)

COST CENTRE             MODULE                                             SRC                                                                          %time %alloc

fmap                    Data.HashMap.Strict.InsOrd                         src/Data/HashMap/Strict/InsOrd.hs:155:15-21                                   16.7   24.6
toList                  Data.HashMap.Strict.InsOrd                         src/Data/HashMap/Strict/InsOrd.hs:(580,1)-(584,22)                            10.8   23.2
hPutChars.loop          Data.Text.IO                                       Data/Text/IO.hs:(190,5)-(193,53)                                              10.6    2.1
typeWithA.loop          Dhall.TypeCheck                                    src/Dhall/TypeCheck.hs:(99,5)-(722,49)                                        10.5    1.9
shift                   Dhall.Core                                         src/Dhall/Core.hs:(585,1)-(738,29)                                             5.3    5.3
fmap                    Data.HashMap.Strict.InsOrd                         src/Data/HashMap/Strict/InsOrd.hs:122:15-21                                    4.4    5.3
subst                   Dhall.Core                                         src/Dhall/Core.hs:(745,1)-(885,29)                                             3.0    2.4
equal                   Data.Text.Lazy                                     Data/Text/Lazy.hs:(301,1)-(312,31)                                             2.6    0.0
compare                 Text.Megaparsec.Pos                                Text/Megaparsec/Pos.hs:127:31-33                                               2.4    0.1
normalizeWith.loop      Dhall.Core                                         src/Dhall/Core.hs:(1265,2)-(1610,22)                                           2.3    1.6
renderIO.go.\           Data.Text.Prettyprint.Doc.Render.Terminal.Internal src/Data/Text/Prettyprint/Doc/Render/Terminal/Internal.hs:(191,29)-(194,23)    2.2    1.0
```
The stuff we’re doing with it seems to be more at the programming edge of Dhall than is common, so I don’t really expect others to be seeing numbers like these, but it’s pretty common for us.

**Comment by Gabriel439** [comment] 2018-05-17 00:50
I also think it's worth mentioning:

https://github.com/dhall-lang/dhall-lang/issues/129

I expect that feature once standardized to lead to the most dramatic speedups in import speed compared to any other improvement (assuming you protect each import with a semantic integrity check, which can be automated)

**Comment by sellout** [comment] 2018-05-17 01:47
Yeah, I think that’ll be great.

At work, we had been talking about having a “build” script to pre-normalize all our files. However, dhall-lang/dhall-lang#129 combined with #392 would give us the same effect without having to manage a build.

**Comment by ocharles** [comment] 2018-10-28 22:30
https://github.com/dhall-lang/dhall-lang/issues/129 is resolved, and this issue only specifically mentions " believe an order of magnitude improvement could be had just by caching the imports." Is that enough to resolve this issue? I worry that otherwise it's slightly unclear what the scope of this issue is other than "make things better" (as worthy as that goal is!)

**Comment by Gabriel439** [comment] 2018-10-28 22:49
I will go ahead and close this in favor of more specific issues since there's not a clear criterion for when this issue is complete

**Closed by Gabriel439** 2018-10-28 22:49 UTC
Labels: performance
